# Paris 2024 Olympics: prediction of winners in  Men's BMX freestyle

This sport was added to olympics program, only during the last olympics in Tokyo.
The data was collected manually from online resources. the prediction make based
on data anlysis.

### The athletes qulified for the event in Paris:

Anthony JeanjeanðŸ‡«ðŸ‡·

Kieran ReillyðŸ‡¬ðŸ‡§

Marcus ChristopherðŸ‡ºðŸ‡¸

Justin DowellðŸ‡ºðŸ‡¸

Gustavo Batista de OliveiraðŸ‡§ðŸ‡·

Marin RantesðŸ‡­ðŸ‡·

## Loading the data files and libraries

In [29]:
import pandas as pd
import matplotlib.pyplot as plt

df_paris = pd.read_csv('data/paris.csv')
df_tokyo = pd.read_csv('data/tokyo.csv')

pd.set_option('display.max_columns', None)

In [30]:
df_paris

,name,country,wikipedia,flag,tokyo-participation,age,shanghai-final-rank,shanghai-qual-run1,shanghai-qual-run2,shanghai-qual-avg,shanghai-final-run1,shanghai-final-run2,shanghai-final-best,budapest-qual-run1,budapest-qual-run2,budapest-qual-avg,budapest-final-run1,budapest-final-run2,budapest-final-best
0,Anthony Jeanjean,France,https://en.wikipedia.org/wiki/Anthony_Jeanjean,ðŸ‡«ðŸ‡·,yes,26,1,86.14,87.37,86.75,93.54,87.82,93.54,85.56,87.63,86.59,93.30,93.40,93.40
1,Kieran Reilly,United Kingdom,https://en.wikipedia.org/wiki/Kieran_Reilly,ðŸ‡¬ðŸ‡§,no,22,3,85.86,84.78,85.32,89.28,28.54,89.28,83.29,85.13,84.21,87.23,92.05,92.05
2,Marcus Christopher,United States,NOT_EXISTS,ðŸ‡ºðŸ‡¸,no,21,11,90.00,88.15,89.07,41.60,74.40,74.40,91.00,87.08,89.04,92.98,21.77,92.98
3,Justin Dowell,United States,https://en.wikipedia.org/wiki/Justin_Dowell,ðŸ‡ºðŸ‡¸,yes,24,6,85.52,78.96,82.24,85.30,39.20,85.30,86.05,83.04,84.54,48.60,90.82,90.82
4,Gustavo Batista de Oliveira,Brazil,https://en.wikipedia.org/wiki/Gustavo_Oliveira,ðŸ‡§ðŸ‡·,no,21,8,84.46,86.06,85.26,84.48,44.40,84.48,88.36,87.58,87.97,89.72,91.90,91.90
5,Marin Rantes,Croatia,NOT_EXISTS,ðŸ‡­ðŸ‡·,no,28,5,82.98,82.78,82.88,87.84,73.60,87.84,79.45,86.73,83.09,88.10,90.80,90.80

In [31]:
df_tokyo

,name,country,flag,final-rating,final-run-1,final-run-2,final-best,seeding-run1,seeding-run2,seeding-average,wikipedia,born,age
0,Logan Martin,Australia,ðŸ‡¦ðŸ‡º,1,93.3,41.4,93.30,91.9,90.04,90.97,https://en.wikipedia.org/wiki/Logan_Martin_(BM...,22 November 1993,30
1,Daniel Dhers,Venezuela,ðŸ‡»ðŸ‡ª,2,90.1,92.05,92.05,84.2,86.00,85.10,https://en.wikipedia.org/wiki/Daniel_Dhers,"March 25, 1985",39
2,Declan Brooks,Great Britain,ðŸ‡¬ðŸ‡§,3,89.4,90.8,90.80,74.3,79.20,76.75,https://en.wikipedia.org/wiki/Declan_Brooks,10 July 1996,27
3,Kenneth Tencio,Costa Rica,ðŸ‡¨ðŸ‡·,4,84.2,90.5,90.50,75.2,84.40,79.80,https://en.wikipedia.org/wiki/Kenneth_Tencio,NOT_EXISTS,NOT_EXISTS
4,Rim Nakamura,Japan,ðŸ‡¯ðŸ‡µ,5,72.2,85.1,85.10,86.2,89.14,87.67,https://en.wikipedia.org/wiki/Rim_Nakamura,9 February 2002,22
5,Irek Rizaev,ROC,â¬œ,6,36.6,82.4,82.40,81.2,81.30,81.25,https://en.wikipedia.org/wiki/Irek_Rizaev,1 October 1997,26
6,Anthony Jeanjean,France,ðŸ‡«ðŸ‡·,7,78.2,51.2,78.20,83.0,86.30,84.65,https://en.wikipedia.org/wiki/Anthony_Jeanjean,13 June 1998,26
7,Justin Dowell,United States,ðŸ‡ºðŸ‡¸,8,44.6,31.6,44.60,69.8,80.60,75.20,https://en.wikipedia.org/wiki/Justin_Dowell,"January 5, 2000",24
8,Nick Bruce,United States,ðŸ‡ºðŸ‡¸,9,24.6,DNS,24.60,6.6,1.00,3.80,https://en.wikipedia.org/wiki/Nick_Bruce,"May 16, 1992",32

In [32]:
df_tokyo.dtypes

name                object
country             object
flag                object
final-rating         int64
final-run-1        float64
final-run-2         object
final-best         float64
seeding-run1       float64
seeding-run2       float64
seeding-average    float64
wikipedia           object
born                object
age                 object
dtype: object

In [33]:
df_paris.dtypes

name                    object
country                 object
wikipedia               object
flag                    object
tokyo-participation     object
age                      int64
shanghai-final-rank      int64
shanghai-qual-run1     float64
shanghai-qual-run2     float64
shanghai-qual-avg      float64
shanghai-final-run1    float64
shanghai-final-run2    float64
shanghai-final-best    float64
budapest-qual-run1     float64
budapest-qual-run2     float64
budapest-qual-avg      float64
budapest-final-run1    float64
budapest-final-run2    float64
budapest-final-best    float64
dtype: object

The prediction is based mainly on the average score of best result in final in the two qualification events in Shanghai and Budapest. the weight that is given to every column during calculation of final prediction score is based on personal estimation.

In [34]:
# penalty - number of scores bellow fifty
scores_columns = ['shanghai-qual-run1','shanghai-qual-run2','shanghai-final-run1','shanghai-final-run2',

                  'budapest-qual-run1','budapest-qual-run2','budapest-final-run1','budapest-final-run2'
                  ]
df_paris['penalty'] = df_paris[scores_columns].apply(lambda x: (x<50).sum(), axis=1)

In [35]:
# Average of best scores in final in both qualification events 
df_paris['avg'] = df_paris[['shanghai-final-best', 'budapest-final-best']].mean(axis=1)

In [36]:
df_paris

,name,country,wikipedia,flag,tokyo-participation,age,shanghai-final-rank,shanghai-qual-run1,shanghai-qual-run2,shanghai-qual-avg,shanghai-final-run1,shanghai-final-run2,shanghai-final-best,budapest-qual-run1,budapest-qual-run2,budapest-qual-avg,budapest-final-run1,budapest-final-run2,budapest-final-best,penalty,avg
0,Anthony Jeanjean,France,https://en.wikipedia.org/wiki/Anthony_Jeanjean,ðŸ‡«ðŸ‡·,yes,26,1,86.14,87.37,86.75,93.54,87.82,93.54,85.56,87.63,86.59,93.30,93.40,93.40,0,93.470
1,Kieran Reilly,United Kingdom,https://en.wikipedia.org/wiki/Kieran_Reilly,ðŸ‡¬ðŸ‡§,no,22,3,85.86,84.78,85.32,89.28,28.54,89.28,83.29,85.13,84.21,87.23,92.05,92.05,1,90.665
2,Marcus Christopher,United States,NOT_EXISTS,ðŸ‡ºðŸ‡¸,no,21,11,90.00,88.15,89.07,41.60,74.40,74.40,91.00,87.08,89.04,92.98,21.77,92.98,2,83.690
3,Justin Dowell,United States,https://en.wikipedia.org/wiki/Justin_Dowell,ðŸ‡ºðŸ‡¸,yes,24,6,85.52,78.96,82.24,85.30,39.20,85.30,86.05,83.04,84.54,48.60,90.82,90.82,2,88.060
4,Gustavo Batista de Oliveira,Brazil,https://en.wikipedia.org/wiki/Gustavo_Oliveira,ðŸ‡§ðŸ‡·,no,21,8,84.46,86.06,85.26,84.48,44.40,84.48,88.36,87.58,87.97,89.72,91.90,91.90,1,88.190
5,Marin Rantes,Croatia,NOT_EXISTS,ðŸ‡­ðŸ‡·,no,28,5,82.98,82.78,82.88,87.84,73.60,87.84,79.45,86.73,83.09,88.10,90.80,90.80,0,89.320

In [37]:
df_paris['avg'] = df_paris[['shanghai-final-best', 'budapest-final-best']].mean(axis=1)

In [38]:
# Bonus for participating at Tokyo Olympics
df_paris['bonus'] = (df_paris['tokyo-participation'] == 'yes').astype(int)

In [39]:
df_paris['prediction_score'] = df_paris['avg'] + df_paris['bonus'] - df_paris['penalty']

In [40]:
df_paris['prediction_score']

0    94.470
1    89.665
2    81.690
3    87.060
4    87.190
5    89.320
Name: prediction_score, dtype: float64

In [41]:
df_paris

,name,country,wikipedia,flag,tokyo-participation,age,shanghai-final-rank,shanghai-qual-run1,shanghai-qual-run2,shanghai-qual-avg,shanghai-final-run1,shanghai-final-run2,shanghai-final-best,budapest-qual-run1,budapest-qual-run2,budapest-qual-avg,budapest-final-run1,budapest-final-run2,budapest-final-best,penalty,avg,bonus,prediction_score
0,Anthony Jeanjean,France,https://en.wikipedia.org/wiki/Anthony_Jeanjean,ðŸ‡«ðŸ‡·,yes,26,1,86.14,87.37,86.75,93.54,87.82,93.54,85.56,87.63,86.59,93.30,93.40,93.40,0,93.470,1,94.470
1,Kieran Reilly,United Kingdom,https://en.wikipedia.org/wiki/Kieran_Reilly,ðŸ‡¬ðŸ‡§,no,22,3,85.86,84.78,85.32,89.28,28.54,89.28,83.29,85.13,84.21,87.23,92.05,92.05,1,90.665,0,89.665
2,Marcus Christopher,United States,NOT_EXISTS,ðŸ‡ºðŸ‡¸,no,21,11,90.00,88.15,89.07,41.60,74.40,74.40,91.00,87.08,89.04,92.98,21.77,92.98,2,83.690,0,81.690
3,Justin Dowell,United States,https://en.wikipedia.org/wiki/Justin_Dowell,ðŸ‡ºðŸ‡¸,yes,24,6,85.52,78.96,82.24,85.30,39.20,85.30,86.05,83.04,84.54,48.60,90.82,90.82,2,88.060,1,87.060
4,Gustavo Batista de Oliveira,Brazil,https://en.wikipedia.org/wiki/Gustavo_Oliveira,ðŸ‡§ðŸ‡·,no,21,8,84.46,86.06,85.26,84.48,44.40,84.48,88.36,87.58,87.97,89.72,91.90,91.90,1,88.190,0,87.190
5,Marin Rantes,Croatia,NOT_EXISTS,ðŸ‡­ðŸ‡·,no,28,5,82.98,82.78,82.88,87.84,73.60,87.84,79.45,86.73,83.09,88.10,90.80,90.80,0,89.320,0,89.320

## Prediction

Gold : Anthony JeanjeanðŸ‡«ðŸ‡·  

Silver: Kieran ReillyðŸ‡¬ðŸ‡§  

Bronze: Marin RantesðŸ‡­ðŸ‡·